[tool.poetry]
name = "thesis"
version = "0.1.0"
description = ""
authors = ["Milan Tichavský <milantichavsky@seznam.cz>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
numpy = "*"
torch = "*"
torchvision = "*"
scipy = "*"
scikit-learn = "*"
pandas = "*"
matplotlib = "*"
mne = "*"
mne-icalabel = "*"
librosa = "*"

[tool.poetry.group.dev.dependencies]
ruff = "*"
ipykernel = "*"
jupyter = "*"
mypy = "*"
pandas-stubs = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 100
lint.select = ["I", "E", "F"]
fix = true

[tool.mypy]
python_version = "3.13"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
disallow_incomplete_defs = false
check_untyped_defs = true
warn_redundant_casts = true
warn_unused_ignores = true
no_implicit_optional = true
strict_equality = true

# Allow untyped calls for third-party libraries without stubs
[[tool.mypy.overrides]]
module = [
    "mne.*",
    "mne_icalabel.*",
    "scipy.*",
    "sklearn.*",
    "matplotlib.*",
    "librosa.*",
]
